version: "3.9"

services:
  db:
    image: mysql
    container_name: db-mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: solita
      MYSQL_DATABASE: db_solita
    volumes:
      - ./db:/var/lib/mysql
      - ./init/:/docker-entrypoint-initdb.d/:ro

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080

  php:
    build: .
    image: myphp:1
    depends_on:
      - db
    ports: 
      - 80:80
    volumes:
      - ./srcs:/var/www/html/

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    links: 
      - db
    ports:
      - 8183:80
